name: 'Build the Unity Runtime'

on:
  push:
    branches:
      - il2cpp-testing
  workflow_dispatch:

permissions:
  packages: write
  contents: write

jobs:
  build-runtime:
    name: 'Build the Unity Runtime'
    runs-on: windows-latest

    steps:
      - name: 'Checkout composite actions'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout: |
            .github

      - name: 'Generate a token'
        id: generate-token
        if: github.event_name != 'pull_request'
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.CI_APP_ID }}
          private-key: ${{ secrets.CI_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: 'Mask generated variable'
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "::add-mask::${{ steps.generate-token.outputs.token }}"

      - name: 'Determine token to use'
        id: token-determination
        shell: bash
        run: |
          TOKEN="${{ github.token }}"

          if [[ "${{ github.event_name }}" != "pull_request" ]]; then
            TOKEN="${{ steps.generate-token.outputs.token }}"
          fi

          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - name: 'Check out repository'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          lfs: 'true'
          path: 'UnityRuntime'
          token: '${{ steps.token-determination.outputs.token }}'
          submodules: ${{ github.event_name != 'pull_request' }}

      - name: 'Remove UMP Directory'
        working-directory: 'UnityRuntime'
        shell: bash
        run: rm -rf Assets/UniversalMediaPlayer

      - name: 'Install Unity'
        uses: buildalon/unity-setup@ab626823a2d32033d5a7811169d0ce92e8010d38 # v2.3.0
        id: unity-setup
        with:
          unity-version: '2019.4.19f1'
          modules: |
            windows-il2cpp
          cache-installation: 'true'

      - name: 'Activate Unity license'
        uses: buildalon/activate-unity-license@ed044477f266bebc3b0bc5270ac3b29782e76116 # v2.1.0
        with:
          license: 'personal'
          username: '${{ secrets.UNITY_CI_USERNAME }}'
          password: '${{ secrets.UNITY_CI_PASSWORD }}'

      - name: 'Build Unity Runtime'
        run: ${{ steps.unity-setup.outputs.unity-editor-path }} -quit -batchmode -nographics -projectPath UnityRuntime/ -buildTarget StandaloneWindows64 -executeMethod AppBuilder.BuildWindowsIL2CPP_Release
        
      - name: 'Upload built artifact'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        path: WindowsIL2CPP/
